"""Generate docs/reference/control_catalogue_table.md from the ontology.

A flat cross-check of the 12 suggested controls against everything they connect
to: the risks that suggest them, the motifs involved, and their MIT taxonomy
links. Useful as a single sheet for review or for a paper table, where the
per-motif view in motif_control_linkage.md is too long.

Two motif columns, deliberately. Exposing = the motif whose presence raises the
risk that suggests this control (the motif is the problem). Realizing = the motif
that structurally implements the control (the motif is the fix). Collapsing them
into one column would read as suggesting a shape as the remedy for itself.

    python python/scripts/generate_control_catalogue_table.py
"""

from __future__ import annotations

import glob
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from rdflib import Graph, Namespace, RDF, SKOS  # noqa: E402

from airiskkg.paths import REPO_ROOT  # noqa: E402

PAIR = Namespace("http://w3id.org/airiskkg/pair-ai#")

# Declaration order in risk_pattern_library.ttl, so the table lines up with the
# file a reviewer would open next to it.
ORDER = [
    "InputValidationAndPromptIsolation",
    "OutputValidationAndSanitization",
    "DataMinimizationAndRedaction",
    "RetrievalAccessControl",
    "ModelAndDependencyProvenance",
    "TrustedTrainingAndIndexingData",
    "ToolPermissionBoundaries",
    "SystemPromptSecrecy",
    "GroundingAndVerification",
    "RateLimitBudgetAndLoopControl",
    "LoggingMonitoringAndEvals",
    "Guardrails",
]


def local(term) -> str:
    return str(term).rsplit("#", 1)[-1]


def main() -> int:
    graph = Graph()
    for path in glob.glob("ontology/patterns/*.ttl") + glob.glob("ontology/core/*.ttl"):
        graph.parse(path)

    controls = [
        s
        for s, _, o in graph.triples((None, RDF.type, None))
        if local(o) == "RiskControl" and "patterns#" in str(s)
    ]
    by_name = {local(c).replace("Control_", ""): c for c in controls}

    lines = [
        "# Suggested Control Catalogue - cross-check table",
        "",
        "Generated by `python/scripts/generate_control_catalogue_table.py` from",
        "`risk_pattern_library.ttl` and `control_mitigation_layer.ttl`. Every cell is read",
        "from the graph; nothing is authored by hand.",
        "",
        "**Two motif columns, deliberately.** *Exposing* = the motif whose presence raises",
        "the risk that suggests this control (the motif is the problem). *Realizing* = the",
        "motif that structurally implements the control (the motif is the fix). Merging them",
        "would read as suggesting a shape as the remedy for itself - and note rows 2, 8 and",
        "12, where `GuardrailsMotif` appears in both columns at once.",
        "",
        "| # | Suggested Control | Related Candidate Risk | Exposing Motif | Realizing Motif | MIT Taxonomy Link |",
        "|---|---|---|---|---|---|",
    ]

    for index, key in enumerate(ORDER, start=1):
        control = by_name[key]
        risks = sorted(
            local(rp).replace("RiskPattern", "")
            for rp in graph.subjects(PAIR.suggestedControl, control)
        )
        exposing = sorted(
            {
                local(m).replace("Motif", "")
                for rp in graph.subjects(PAIR.suggestedControl, control)
                for m in graph.objects(rp, PAIR.hasMotif)
            }
        )
        realizing = sorted(
            local(m).replace("Motif", "")
            for m in graph.objects(control, PAIR.realizedByMotif)
        )
        taxonomy = sorted(local(o) for o in graph.objects(control, SKOS.relatedMatch))
        label = str(graph.value(control, SKOS.prefLabel))

        lines.append(
            f"| {index} "
            f"| **{label}**<br>`pat:{local(control)}` "
            f"| {', '.join(risks)} "
            f"| {', '.join(exposing) or '(none)'} "
            f"| {'**' + ', '.join(realizing) + '**' if realizing else '(none)'} "
            f"| {', '.join(taxonomy)} |"
        )

    lines += [
        "",
        "## Reading the gaps",
        "",
        f"- **All {len(controls)} controls carry MIT links.** None is unmapped; the "
        "`pat:Control_*` to `mitctrl:*` hop is complete, not outstanding.",
        f"- **Only {sum(1 for c in controls if list(graph.objects(c, PAIR.realizedByMotif)))} "
        "of 12 have a realizing motif.** For the rest the tool can advise the control but "
        "cannot verify from the graph that it was applied.",
        "- **Row 11 is near-universal.** `LoggingMonitoringAndEvals` is suggested by 9 of 13 "
        "risk patterns, so its presence in a findings list carries little discriminating "
        "information.",
        "- **Rows 2, 8, 12 are circular.** `GuardrailsMotif` both realizes the control and "
        "triggers the risk that suggests it.",
    ]

    target = REPO_ROOT / "docs" / "reference" / "control_catalogue_table.md"
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
